/*Copyright (c) 2019-2020 reddcoin2.com All Rights Reserved.
 This software is the confidential and proprietary information of reddcoin2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with reddcoin2.com*/
import com.nuevo.sql3273776.*:;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import com.nuevo.sql3273776.Usuarios;
import java.io.Serializable;
/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


@Repository("usuariosRepository")
public interface UsuarioRepository extends JpaRepository<Usuarios, Serializable> {
	public abstract Usuarios findByUsuario(String usuario);
	
}