/*Copyright (c) 2019-2020 reddcoin2.com All Rights Reserved.
 This software is the confidential and proprietary information of reddcoin2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with reddcoin2.com*/
package com.nuevo.sql3273776;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`USUARIOS`")
public class Usuarios implements Serializable {

    private Integer id;
    private String usuario;
    private String password;
    private String rol;
    private String activo;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`USUARIO`", nullable = true, length = 255)
    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Column(name = "`PASSWORD`", nullable = true, length = 255)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "`ROL`", nullable = true, length = 255)
    public String getRol() {
        return this.rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    @Column(name = "`ACTIVO`", nullable = true, length = 255)
    public String getActivo() {
        return this.activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Usuarios)) return false;
        final Usuarios usuarios = (Usuarios) o;
        return Objects.equals(getId(), usuarios.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}